name: PHPUnit Test

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1']
        db_driver: ['mysqli', 'pdo_mysql', 'sqlite3'] # Sesuaikan dengan kebutuhan driver Anda

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: ci_test
        ports:
          - 3306:3306

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mysqli, pdo, pdo_mysql, sqlite3, mbstring
          coverage: none

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHPUnit Tests
        # Perhatikan: -c mengarah ke folder tests/phpunit.xml anda
        run: vendor/bin/phpunit -c tests/phpunit.xml
        env:
          DB_DRIVER: ${{ matrix.db_driver }}
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASS: ''
          DB_NAME: ci_test